name: corner_driven_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - numba
  - h5py
  - pip
  - pip:
      - pytket==2.9.1 
      - pytket-quantinuum==0.52.0
      - pytket-quantinuum[pecos]
      - qnexus==0.32.0